config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get 'home/about'=>"homes#about"
  get '/search' => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]

  end


  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
    end
    resource :relationships, only: [:create,:destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = Favorite.new(user_id: current_user.id, book_id: params[:book_id])
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = Favorite.find_by(user_id: current_user.id, book_id: params[:book_id])
    favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= form_with model: @favorite, url: book_favorites_path(book.id), method: :delete, local: false  do |f| %>
  <%= f.hidden_field :book_id, value: book.id %>
    <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <snap class="text-danger"><%= book.favorites.count %></snap>
    <% end %>
  <% end %>
<% else %>
  <%= form_with model: @favorite, url: book_favorites_path(book.id), method: :post, local: false  do |f| %>
  <%= f.hidden_field :book_id, value: book.id %>
    <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: blue;"></i>
    <snap class="text-primary"><%= book.favorites.count %></snap>
    <% end %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
  $('#favorite-btn-<%= @book.id %>').html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");