config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get 'home/about'=>"homes#about"
  get '/search' => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]

  end


  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
    end
    resource :relationships, only: [:create,:destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  #following user
  def follow(other_user)
   active_relationships.create(followed_id: other_user)
  end

  #unfollowing user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user).destroy
  end

  #if current_user is following retrun true
  def following?(user)
    following.include?(user)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE ?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
       @user = User.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    @user = User.find(current_user.id)

  end

  def edit
    @user= User.find(params[:id])
    if @user.id != current_user.id
    redirect_to user_path(current_user.id)
    end
  end

  def update
    @user= User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end





  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with model: @relationship, url: user_relationships_path(@user.id)  do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == user %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '80x80' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% unless current_user == user %>
          　  <% if current_user.following?(user) %>
                <%= link_to "フォローを外す", user_relationships_path(user), method: :delete %>
            <% else %>
                <%= link_to "フォローする",user_relationships_path(user), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <%= render 'users/stats', user: @user %>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_stats.html.erb
<tr>

  <th>follows</th>
  <th>
    <a href = '<%= following_user_path(user.id) %>'>
      <%= user.following.count %>
    </a>
  </th>
</tr>
<tr>
  <th>followers</th>
  <th>
    <a href = '<%= followers_user_path(user) %>'>
        <%= user.followers.count %>
    </a>
  </th>
</tr>

app/views/users/_unfollow.html.erb
<%= form_with model: @relationship, url: user_relationships_path(@user.id), method: :delete do |f| %>
 <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Unfollow", class: "btn btn-secondary" %>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div> 
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users, user: @user %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <div class="mt-3">
      <%= render 'follow_form', user: @user %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book%>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-12">
    <h2>Follow Users</h2>
      <table class='table'>
        <thead>
         <% if @user.following.count == 0 %>
          <div>ユーザーはいません</div>
         <% else %>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.get_profile_image, size: '80x80' %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.following.count %></td>
                <td>フォロワー数：<%= user.followers.count %></td>
                <td><%= link_to 'Show', user_path(user.id) %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show_follower.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-12">
    <h2>Follower Users</h2>
      <table class='table'>
        <thead>
         <% if @user.followers.count == 0 %>
          <div>ユーザーはいません</div>
         <% else %>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image, size: '80x80' %></td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.following.count %></td>
              <td>フォロワー数：<%= user.followers.count %></td>
              <td><%= link_to 'Show', user_path(user.id) %></td>
            </tr>
          <% end %>
       <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>