config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get 'home/about'=>"homes#about"
  get '/search' => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]

  end


  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
    end
    resource :relationships, only: [:create,:destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence:true
  validates :body, presence:true, length:{maximum:200}

  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE ?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
  
  
  
  
  
  
  
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)
    @book_comment = BookComment.new
    @book_comments = BookComment.all
  end


  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: book, local: true do |f| %>
  <div class= "form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class= "form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class= "form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class= "table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan= "3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size: '80x80' %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td id= "favorite-btn-<%= book.id %>">
          <%= render 'favorites/favorite-btn', book: book %>
        </td>
        <td>
          コメント数:<%= book.book_comments.count %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/books/edit.html.erb
<div class= "container">
  <%= render 'layouts/errors', obj: @book %>
  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: 'back' %>
  </div>
</div>

app/views/books/index.html.erb
<div class= "container px-5 px-sm-0">
<%= render 'layouts/errors', obj: @book %>
  <div class= "row">
    <div class= "col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class= "mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class= "col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'index', books: @books, book_comments: @book_comments %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class= "container">
  <div class= "row">
    <div class= "col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class= "mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class= "col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class= "table">
  		  <tr id= "book_<%= @book.id %>">
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size: '100x100' %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td id= "favorite-btn-<%= @book.id %>"><%= render 'favorites/favorite-btn', book: @book %></td>
          <td  class= "comments-count">コメント数:<%= @book.book_comments.count %></td>
          <% if @book.user.id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-sm btn-success' %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: 'btn btn-sm btn-danger' %></td>
          <% end %>
        </tr>
      </table>
      <table class= "book_comment-<%= @book.id %>">
      <%= render 'book_comments/book_comment',  book: @book, book_comment: @book_comment %>
      </table>
      <div >
        <%= form_with model: @book_comment, url: book_book_comments_path(@book.id), local: false do |f| %>
        <%= f.text_area :comment, rows: "5" ,class: 'form-control form-control-lg mb-3' %>
        <%= f.submit '送信' , class: 'btn btn-primary', id: "submit" %>
        <% end %>
      </div>
    </div>
  </div>
</div>